import { ThemePalette } from "../types";

export const DOCS_BUCKET = "travel-documents";

export const THEME_PALETTES: Record<
  ThemePalette,
  {
    lightBg: string;
    lightCard: string;
    lightAccent: string;
    lightSidebarBg: string;
    lightSidebarBorder: string;
    lightSidebarText: string;
    lightSidebarHover: string;
    lightSidebarActiveBg: string;
    lightSidebarActiveText: string;
    darkBg: string;
    darkCard: string;
    darkAccent: string;
    darkSidebarBg: string;
    darkSidebarBorder: string;
    darkSidebarText: string;
    darkSidebarHover: string;
    darkSidebarActiveBg: string;
    darkSidebarActiveText: string;
  }
> = {
  default: {
    lightBg: "#F8F9FA",
    lightCard: "#FFFFFF",
    lightAccent: "#0A2342",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#E5E7EB",
    lightSidebarText: "#3F3F46",
    lightSidebarHover: "#F4F4F5",
    lightSidebarActiveBg: "#0A2342",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#0A2342",
    darkCard: "#162E4D",
    darkAccent: "#5BC0EB",
    darkSidebarBg: "#0A2342",
    darkSidebarBorder: "#1E3A5F",
    darkSidebarText: "#E4E4E7",
    darkSidebarHover: "#162E4D",
    darkSidebarActiveBg: "#5BC0EB",
    darkSidebarActiveText: "#0A2342",
  },
  ocean: {
    lightBg: "#F0F7FF",
    lightCard: "#FFFFFF",
    lightAccent: "#0284C7",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#E0F2FE",
    lightSidebarText: "#0369A1",
    lightSidebarHover: "#F0F9FF",
    lightSidebarActiveBg: "#0284C7",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#082F49",
    darkCard: "#0C4A6E",
    darkAccent: "#7DD3FC",
    darkSidebarBg: "#082F49",
    darkSidebarBorder: "#0E7490",
    darkSidebarText: "#E0F2FE",
    darkSidebarHover: "#0C4A6E",
    darkSidebarActiveBg: "#7DD3FC",
    darkSidebarActiveText: "#082F49",
  },
  forest: {
    lightBg: "#F0FDF4",
    lightCard: "#FFFFFF",
    lightAccent: "#166534",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#DCFCE7",
    lightSidebarText: "#14532D",
    lightSidebarHover: "#F0FDF4",
    lightSidebarActiveBg: "#166534",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#052E16",
    darkCard: "#064E3B",
    darkAccent: "#86EFAC",
    darkSidebarBg: "#052E16",
    darkSidebarBorder: "#065F46",
    darkSidebarText: "#DCFCE7",
    darkSidebarHover: "#064E3B",
    darkSidebarActiveBg: "#86EFAC",
    darkSidebarActiveText: "#052E16",
  },
  sunset: {
    lightBg: "#FFF7ED",
    lightCard: "#FFFFFF",
    lightAccent: "#C2410C",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#FFEDD5",
    lightSidebarText: "#9A3412",
    lightSidebarHover: "#FFF7ED",
    lightSidebarActiveBg: "#C2410C",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#431407",
    darkCard: "#7C2D12",
    darkAccent: "#FDBA74",
    darkSidebarBg: "#431407",
    darkSidebarBorder: "#9A3412",
    darkSidebarText: "#FFEDD5",
    darkSidebarHover: "#7C2D12",
    darkSidebarActiveBg: "#FDBA74",
    darkSidebarActiveText: "#431407",
  },
  lavender: {
    lightBg: "#F5F3FF",
    lightCard: "#FFFFFF",
    lightAccent: "#6D28D9",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#EDE9FE",
    lightSidebarText: "#5B21B6",
    lightSidebarHover: "#F5F3FF",
    lightSidebarActiveBg: "#6D28D9",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#2E1065",
    darkCard: "#4C1D95",
    darkAccent: "#DDD6FE",
    darkSidebarBg: "#2E1065",
    darkSidebarBorder: "#5B21B6",
    darkSidebarText: "#EDE9FE",
    darkSidebarHover: "#4C1D95",
    darkSidebarActiveBg: "#DDD6FE",
    darkSidebarActiveText: "#2E1065",
  },
  midnight: {
    lightBg: "#F8FAFC",
    lightCard: "#FFFFFF",
    lightAccent: "#0F172A",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#E2E8F0",
    lightSidebarText: "#1E293B",
    lightSidebarHover: "#F1F5F9",
    lightSidebarActiveBg: "#0F172A",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#020617",
    darkCard: "#0F172A",
    darkAccent: "#94A3B8",
    darkSidebarBg: "#020617",
    darkSidebarBorder: "#1E293B",
    darkSidebarText: "#CBD5E1",
    darkSidebarHover: "#0F172A",
    darkSidebarActiveBg: "#94A3B8",
    darkSidebarActiveText: "#020617",
  },
  rose: {
    lightBg: "#FFF1F2",
    lightCard: "#FFFFFF",
    lightAccent: "#BE123C",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#FFE4E6",
    lightSidebarText: "#9F1239",
    lightSidebarHover: "#FFF1F2",
    lightSidebarActiveBg: "#BE123C",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#450A0A",
    darkCard: "#881337",
    darkAccent: "#FDA4AF",
    darkSidebarBg: "#450A0A",
    darkSidebarBorder: "#9F1239",
    darkSidebarText: "#FFE4E6",
    darkSidebarHover: "#881337",
    darkSidebarActiveBg: "#FDA4AF",
    darkSidebarActiveText: "#450A0A",
  },

  // LAYOUT FIX: Novo tema — Tropic (verde tropical)
  tropic: {
    lightBg: "#F0FDF7",
    lightCard: "#FFFFFF",
    lightAccent: "#059669",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#D1FAE5",
    lightSidebarText: "#065F46",
    lightSidebarHover: "#F0FDF7",
    lightSidebarActiveBg: "#059669",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#022C22",
    darkCard: "#064E3B",
    darkAccent: "#34D399",
    darkSidebarBg: "#022C22",
    darkSidebarBorder: "#047857",
    darkSidebarText: "#A7F3D0",
    darkSidebarHover: "#064E3B",
    darkSidebarActiveBg: "#34D399",
    darkSidebarActiveText: "#022C22",
  },

  // LAYOUT FIX: Novo tema — Aurora (âmbar + meia-noite)
  aurora: {
    lightBg: "#FAFAF5",
    lightCard: "#FFFFFF",
    lightAccent: "#D97706",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#FEF3C7",
    lightSidebarText: "#92400E",
    lightSidebarHover: "#FFFBEB",
    lightSidebarActiveBg: "#D97706",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#0C1445",
    darkCard: "#1E2A6E",
    darkAccent: "#FCD34D",
    darkSidebarBg: "#0C1445",
    darkSidebarBorder: "#1E3A5F",
    darkSidebarText: "#E0E7FF",
    darkSidebarHover: "#1E2A6E",
    darkSidebarActiveBg: "#FCD34D",
    darkSidebarActiveText: "#0C1445",
  },

  // LAYOUT FIX: Novo tema — Coastal (azul moderno, versão aprimorada do Ocean)
  coastal: {
    lightBg: "#F0F9FF",
    lightCard: "#FFFFFF",
    lightAccent: "#0369A1",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#BAE6FD",
    lightSidebarText: "#0C4A6E",
    lightSidebarHover: "#F0F9FF",
    lightSidebarActiveBg: "#0369A1",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#0F1C2E",
    darkCard: "#162944",
    darkAccent: "#22D3EE",
    darkSidebarBg: "#0F1C2E",
    darkSidebarBorder: "#1E3A5F",
    darkSidebarText: "#BAE6FD",
    darkSidebarHover: "#162944",
    darkSidebarActiveBg: "#22D3EE",
    darkSidebarActiveText: "#0F1C2E",
  },

  // LAYOUT FIX: Novo tema — Terra (siena + carvão quente)
  terra: {
    lightBg: "#FAF5EF",
    lightCard: "#FFFFFF",
    lightAccent: "#92400E",
    lightSidebarBg: "#FFFFFF",
    lightSidebarBorder: "#FDE68A",
    lightSidebarText: "#78350F",
    lightSidebarHover: "#FEF9EE",
    lightSidebarActiveBg: "#92400E",
    lightSidebarActiveText: "#FFFFFF",
    darkBg: "#1C1917",
    darkCard: "#292524",
    darkAccent: "#F59E0B",
    darkSidebarBg: "#1C1917",
    darkSidebarBorder: "#44403C",
    darkSidebarText: "#D6D3D1",
    darkSidebarHover: "#292524",
    darkSidebarActiveBg: "#F59E0B",
    darkSidebarActiveText: "#1C1917",
  },
};

export const ACTIVITY_ICONS = [
  "Calendar",
  "Plane",
  "Bus",
  "Train",
  "Ship",
  "Car",
  "Hotel",
  "Utensils",
  "Coffee",
  "ShoppingBag",
  "Camera",
  "MapPin",
  "Music",
  "Ticket",
  "Umbrella",
  "Mountain",
  "Waves",
  "Palmtree",
  "Wine",
  "Beer",
  "Footprints",
  "Bike",
  "Theater",
  "Landmark",
  "Castle",
  "Church",
  "Stethoscope",
  "Briefcase",
];
